### PR TITLE
Replace `excludedTables`/`includedTables` with glob-enabled `tables` option

### PR DESCRIPTION
**Pull request by adambiggs**
This PR lets you include/exclude tables form a backup using glob strings on a new `tables` option, powered by [`multimatch`](https://github.com/sindresorhus/multimatch).

### CODE REVIEW

**Comment by dylanlingelbach** [comment]
@adambiggs - I like this. Any thoughts on keeping but deprecating the old options and converting those params to the new format?

**Comment by allenhartwig** [comment]
Really looking for this feature. @dylanlingelbach would you merge if I opened a new PR that retained legacy support for `-x` and `-i`?

**Comment by adambiggs** [comment]
@allenhartwig I can add you as a collaborator to my fork if you want to just update this PR

**Comment by dylanlingelbach** [comment]
@allenhartwig yes, would merge this if legacy support was kept without breaking changes

**Pull request closed without merging**
