### PR TITLE
Dynamo Restore

### PR DESCRIPTION
**Pull request by sdesalas**
Hiya, here is a sidekick restore process for you backup. Hope you find it useful.

### CODE REVIEW

**Comment by dylanlingelbach** [comment]
@sdesalas did you mean to close this? I'd definitely be interested in adding this PR as I've had several requests for restore functionality.

No worries if it just wasn't ready

**Comment by sdesalas** [comment]
No problem. Theres a conflict with repo as I forked one of the child forks. I thought I'd have some time to resolve it but feel free to merge if you can take time to fix conflicts.

**Comment by sdesalas** [comment]
Hi @dylanlingelbach,

I've now resolved the conflict this pull request had.

I also had a chance to use this in a prod environment restoring dynamo backups of up ot 2GB (20 minutes using EC2 instance), and fixed a legacy issue on node v0.10.

All good to merge on my part. Go ahead if you feel comfortable.

Kind Regards,
Steven

**Comment by sdesalas** [comment]
Hi @dylanlingelbach,

I've now resolved the conflict this pull request had.

I also had a chance to use this in a prod environment restoring dynamo backups of up ot 2GB (20 minutes using EC2 instance - main bottleneck is S3 streaming download speed), and fixed a legacy issue on node v0.10.

All good to merge on my part. Go ahead if you feel comfortable.

Kind Regards,
Steven

**Comment by dylanlingelbach** [comment]
@sdesalas great, I will try to take a look this week

**Comment by dylanlingelbach** [comment]
@sdesalas could you convert tabs to spaces?

**Comment by sdesalas** [comment]
Hi Dylan. 

All good on this end. Let me know if you need anything else.

**Comment by dylanlingelbach** [comment]
@sdesalas sorry for the huge delay here - merging now. Will publish as version 0.6.0

**Comment by sdesalas** [comment]
:dancing_men:

**Pull request merged**
